/**
 * Template merge engine. Templates are owner-editable with {{merge_fields}}
 * and versioned — every sent step records the version actually used, so a
 * recovery pack can reproduce exactly what went out.
 *
 * Default template *content* below is engineering placeholder text written
 * in the product's deliberately impersonal, administrative register. It must
 * be reviewed and approved by the owner (a qualified barrister) before
 * launch — see handover §4.2 and §9.1.
 */

import { formatCents } from "./money";
import { formatDate } from "./dates";
import {
  FeeNote,
  Matter,
  SolicitorContact,
  SolicitorFirm,
  Template,
  UserProfile,
} from "./types";

export interface MergeContext {
  user: UserProfile;
  feeNote: FeeNote;
  matter: Matter;
  firm: SolicitorFirm;
  contact: SolicitorContact | null;
  ageDays: number;
  outstandingCents: number;
}

export function mergeFields(ctx: MergeContext): Record<string, string> {
  return {
    barrister_name: ctx.user.fullName,
    barrister_email: ctx.user.email,
    law_library_no: ctx.user.lawLibraryNo,
    fee_note_number: ctx.feeNote.number,
    fee_note_amount: formatCents(ctx.feeNote.amountCents),
    outstanding_amount: formatCents(ctx.outstandingCents),
    issue_date: formatDate(ctx.feeNote.issueDate),
    age_days: String(ctx.ageDays),
    matter_title: ctx.matter.title,
    matter_reference: ctx.matter.reference,
    firm_name: ctx.firm.name,
    solicitor_name: ctx.contact?.name ?? "the instructing solicitor",
    today: formatDate(new Date().toISOString()),
  };
}

/** Replace {{field}} tokens; unknown fields are left visible so a bad
 * template is caught at preview, not silently sent blank. */
export function renderTemplate(text: string, fields: Record<string, string>): string {
  return text.replace(/\{\{\s*([a-z_]+)\s*\}\}/g, (whole, name) =>
    name in fields ? fields[name] : whole,
  );
}

export function renderForFeeNote(template: Template, ctx: MergeContext) {
  const fields = mergeFields(ctx);
  return {
    subject: renderTemplate(template.subject, fields),
    body: renderTemplate(template.body, fields),
  };
}

// ---------------------------------------------------------------------------
// Default templates (placeholder content — owner review required pre-launch)
// ---------------------------------------------------------------------------

export const DEFAULT_TEMPLATES: Omit<Template, "id" | "updatedAt">[] = [
  {
    kind: "REMINDER_1",
    name: "First reminder (day 30)",
    version: 1,
    subject: "Fee note {{fee_note_number}} — payment reminder",
    body: `Dear {{solicitor_name}},

Our records show that fee note {{fee_note_number}} in the matter of {{matter_title}} ({{matter_reference}}), issued on {{issue_date}} in the amount of {{fee_note_amount}}, remains outstanding.

This is an automated reminder generated by {{barrister_name}}'s practice management system. If payment has already been made, please disregard this notice.

Kind regards,
Practice administration for {{barrister_name}} BL`,
  },
  {
    kind: "REMINDER_2",
    name: "Second reminder (day 60)",
    version: 1,
    subject: "Fee note {{fee_note_number}} — second reminder ({{age_days}} days outstanding)",
    body: `Dear {{solicitor_name}},

Fee note {{fee_note_number}} in the matter of {{matter_title}} ({{matter_reference}}) has now been outstanding for {{age_days}} days. The amount outstanding is {{outstanding_amount}}.

Please arrange payment, or contact this office if there is any query on the fee note.

Kind regards,
Practice administration for {{barrister_name}} BL`,
  },
  {
    kind: "FORMAL_LETTER",
    name: "Formal aged-fee letter (day 90)",
    version: 1,
    subject: "Formal notice — fee note {{fee_note_number}} outstanding {{age_days}} days",
    body: `Dear {{solicitor_name}},

Re: {{matter_title}} ({{matter_reference}}) — fee note {{fee_note_number}}

Despite previous reminders, fee note {{fee_note_number}} issued on {{issue_date}} remains unpaid. The amount outstanding is {{outstanding_amount}}.

Unless payment is received or a query is raised within 14 days of the date of this letter, {{barrister_name}} will have no alternative but to consider referral of this matter to the Bar of Ireland's fee recovery service and/or a complaint to the Legal Services Regulatory Authority.

This letter and the full chronology of correspondence on this fee note are retained on file.

Yours faithfully,
{{barrister_name}} BL`,
  },
  {
    kind: "SECTION_150",
    name: "Section 150 notice",
    version: 1,
    subject: "Notice under section 150 of the Legal Services Regulation Act 2015 — {{matter_title}}",
    body: `[PLACEHOLDER — Section 150 notice content to be drafted and approved by the owner before launch. Engineering builds the engine; content is owner-supplied.]

Matter: {{matter_title}} ({{matter_reference}})
Instructing firm: {{firm_name}}
Barrister: {{barrister_name}} BL, Law Library No. {{law_library_no}}
Date: {{today}}`,
  },
];
